init define mc = DynamicCharacter("name", color="#ffaf05")
init define js = Character("Josy", color="#ff1c63")
init define my = Character("Maya", color = "#a7f442")
init define sa = Character("Sage", color = "#BCB88A")
init define isa = Character("Isabella", color="#d8f2ff")
init define ice = Character("Królowa Lodu", color="#d8f2ff")
init define qu = Character("Quinn", color="#a0abff")
init define ca = Character("Cathy", color="#ff3d0c")
init define cam = Character("Camila", color="#c55ffc")
init define ri = Character("Riona", color="#6b6461")
init define ja = Character("Jade", color="#357d1c")
init define ji = Character("Jill", color="#ffe9b9")
init define bu = Character("Profesor Burke", color="bc9360")
init define sb = Character("Stephen", color="bc9360")
init define tm = Character("Tommy", color="#9e5900")
init define rs = Character("Rusty", color="#ff5630")
init define jac = Character("Jacob", color="#dba42e")
init define jm = Character("Jamie", color="#f4e842")
init define le = Character("Leon", color="#c16000")
init define ni = Character("Nick", color="#ffc023")
init define jb = Character("John Boy", color="#fced1b")
init define an = Character("Anthony", color="#5623ff")
init define ch = Character("Chad", color="#23b4fc")
init define dw = Character("Dawe", color= "#45ebf7")
init define mg = Character("Magnar", color="#c700dd")
init define sy = Character("Sally", color="#d450d8")
init define rn = Character("Ron", color="#683b89")
init define eu = Character("Eugene", color="#620251")
init define tri = Character("Tri-betas", color="#d450d8")
init define ty = Character("Tybalt", color="#87fa5a")
init define rich = Character("Rich", color="#83f97c")
init define tr = Character("Trent", color="#229c67")
init define lu = Character("Lucas", color="#289460")
init define go = Character("Gordon", color="#03a329")
init define ml = Character("Melanie", color="#ff99cc")
init define sar = Character("Sarah", color="#ee134a")
init define el = Character("Elena", color="#a333a5")
init define mn = Character("Mona", color="#a333a5")
init define ar = Character("Arieth", color="#FF906A")
init define he = Character("Heather", color="#f7dfc8")
init define beth = Character("Beth", color="a9f2b4")
init define bo = Character("Bouncer", color="#ff0000")
init define stan = Character("Stanley", color="#ff0000")
init define de = Character("Derek", color="#0066ff")
init define dn = Character("Dany", color="#ab54f7")
init define dpc = Character("Dr PinkCake", color="#ff7ffa")
init define dad = Character("Neil", color= "#0cf977")
init define dad2 = Character("Tata", color= "#0cf977")
init define troy = Character("Troy", color="#ff0000")
init define st = Character("Steve", color="#f7dfc8")
init define kid = Character("Dziecko")
init define wen = Character("Wendy", color="#c613c3")
init define mi = Character("Minny", color="#b723a5")
init define mon = Character("Monica", color="#ab54f7")
init define pt = Character("Pete", color="#42eef4")
init define tn = Character("Tina", color="#42eef4")
init define ash = Character("Ashley", color="#42eef4")
init define en = Character("Envy", color="#42f450")
init define ro = Character("Rose", color="#d11b42")
init define ly = Character("Lily", color="#d749ff")
init define br = Character("Brandi", color="#76fcd1")
init define sn = Character("Sandy", color="#b7a07b")
init define girl = Character("Dziewczyna", color="a9f2b4")
init define be = Character("Bert", color="#f7dfc8")
init define hg = Character("Dziewczyna HOT", color ="#ce588f")
init define bt = Character("Bartender", color ="#a9f2b4")
init define rc = Character("Recepcionista", color="a9f2b4")
init define ll = Character("Pracownik stołówki", color="a9f2b4")
init define uk = Character("Nieznany", color="#f7dfc8")
init define jc = Character("Jock", color="#5623ff")
init define jcs = Character("Jocks", color="#5623ff")
init define dikc = Character("DIK", color="#ffc666")
init define dikcs = Character("DIKs", color="#ffc666")
init define cl = Character("Clerk", color="#f7dfc8")
init define bs = Character("Szef", color="#f7dfc8")
init define cs = Character("Klient", color="#f7dfc8")
init define cs2 = Character("Starsza pani", color="#f7dfc8")
init define sec = Character("Ochroniarz", color="#f7dfc8")
init define stu = Character("Student", color="#ec5c5c")
init define fem = Character("Feministka", color="#c613c3")
init define prep = Character("Prep", color="#76f422")
init define prepp = Character("Prep pledger", color="#76f422")
init define maid = Character("Maid")
init define wife = Character("Żona")
init define husband = Character("Mąż")
return